{% set name = "epix-hr-m-320k" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///cds/home/c/cpo/junk/junk/{{ name }}-{{ version }}.tar.gz
  sha256: ee6c04817cd6827b27ce2834625cc5c63e694dd597d8e248d8972cec1efa320a
  patches:
    - setup.patch

build:
  skip: True  # [win or osx]
  noarch: python
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

about:
  home: https://github.com/slaclab/epix-hr-m-320k
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Epix HR M 320k software and firmware'
  description: |
    firmware for Epix HR M 320k devices.
  doc_url: https://github.com/slaclab/epix-hr-m-320k
  dev_url: https://github.com/slaclab/epix-hr-m-320k

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

